name: CI-CD

on:
  push:
    branches: [ main ]
    paths: [ "webapp/**" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'a9ojg5e34mhhluds-wapp'
  ARTIFACT_NAME: webapp-dist

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifactname: ${{ env.ARTIFACT_NAME }}
  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Downloads the build artifact
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}

      # Deploy to Azure Web apps
      - name: app service deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '.'
