name: Deploy PR Slot

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths: [ "webapp/**" ]
  workflow_dispatch:

env:
  RESOURCE_GROUP: 'csa-appservice'
  AZURE_WEBAPP_NAME: 'a9ojg5e34mhhluds-wapp'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifactname: webapp-dist

  deploy-slot:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Downloads the build artifact
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp-dist

      # Create App Service slot
      - name: create app service slot
        uses: azure/CLI@v1
        with:
          azcliversion: 2.35.0
          inlineScript: |
            az webapp deployment slot create \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --slot pr${{ github.event.number }} \
              --configuration-source ${{ env.AZURE_WEBAPP_NAME }}

      # Deploy to Azure Web apps
      - name: app service deploy
        uses: azure/webapps-deploy@v2
        with:
          slot-name: pr${{ github.event.number }}
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '.'
